apiVersion: v2
name: ocis
description: ownCloud Infinite Scale (oCIS) Helm chart
keywords:
  - owncloud
  - ocis
maintainers:
  - name: ownCloud GmbH
    email: devops@owncloud.com
    url: https://owncloud.com
type: application
version: 0.7.0
# renovate: datasource=docker depName=owncloud/ocis
appVersion: 7.1.3
dependencies:
  - name: nats
    version: "1.3.9" # Use the latest stable version or the one you need
    repository: "https://nats-io.github.io/k8s/helm/charts/"
    condition: nats.enabled
kubeVersion: "" # please see https://doc.owncloud.com/ocis/next/deployment/container/orchestration/orchestration.html#get-the-chart for compatible Kubernetes versions
sources:
  - https://github.com/owncloud/ocis-charts
  - https://github.com/owncloud/ocis
  - https://github.com/cs3org/reva
